name: 'tests and coverage'
on: pull_request #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/coverage-final.json
          fail_ci_if_error: true
          verbose: true
